### ISSUE TITLE
Magic Carpet 2

### ISSUE THREAD

**Issue by turican0** [opengaming/osgameclones#617] opened 2018-08-25 10:28 UTC
Magic Carpet 2

```yaml
- name:remc2
  type:remake
  originals: [Magic Carpet 2]
  repo:https://github.com/turican0/remc2
  url:https://github.com/turican0/remc2/wiki
  feed:
  development:Active
  status:Unplayable
  multiplayer: []
  lang: [c++]
  framework: []
  license: GPL3
  content:
  info:
  updated:
  images:https://github.com/turican0/remc2/wiki
    -
  video:https://github.com/turican0/remc2/wiki
    youtube:
    vimeo:
```

**Comment by cxong** [comment] 2019-02-21 00:10
Duplicate of #658

**Closed by cxong** 2019-02-21 00:10 UTC
